import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Button from "./components/shared/Button";

const Home: NextPage = () => {
  const { push } = useRouter();

  const handleClick = () => {
    push("#about");
  };

  return (
    <div className="antialiased">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section
          id="intro"
          className="bg-gray-800 text-white flex flex-1 flex-col justify-center items-center min-h-screen"
        >
          <div className="flex flex-col space-y-4 ...">
            <p className="text-slate-300">Hello, I am</p>
            <h1 className="text-8xl">Caio De Blasio</h1>
            <p className="text-6xl">I build stuff for the Web</p>
            <Button variant={Button.variant.OUTLINED} onClick={handleClick}>
              About me
            </Button>
          </div>
        </section>
        <section
          id="about"
          className="flex flex-1 flex-col justify-center items-center min-h-screen"
        >
          <h1 className="text-8xl">About</h1>
        </section>
      </main>
    </div>
  );
};

export default Home;
